### ISSUE TITLE
[PE-D] Cross doesn't display properly

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-W09-4/tp#164]
![image.png](https://raw.githubusercontent.com/snss231/ped/main/files/72e5196c-8d93-4f92-9dd7-abcbea315391.png)

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: snss231/ped#11

**Comment by Korochii** [comment]
@medajet to test on mac

**Comment by medajet** [comment]
> @medajet to test on mac

It seems like the tick appears correctly, but the cross appears slightly cut off. See the screenshot for illustration:

<img width="743" alt="Screenshot 2022-04-03 at 19 38 38" src="https://user-images.githubusercontent.com/25050392/161426204-6d43ce03-015b-4d28-a0a7-357793259350.png">

Might not be a massive issue since it still recognisably appears as a cross, just that the color might come across as odd.

**Comment by Korochii** [comment]
![image](https://user-images.githubusercontent.com/65613207/161427982-7c4f08da-9c96-4ff4-ba09-18bf88d7ed29.png)

No issues on Linux as well. Will be closing this issue...
